import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Crogecoin",
  description: "Generated by create crogecoin",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-sans overflow-x-hidden`}>
        <main>
          {children}
          <span className="absolute border-[2px] border-[#fff] bg-[#fff] top-[1110px] md:top-[630px] lg:top-[670px] xl:top-[735px] 2xl:top-[790px] left-0 w-[100vw] -z-[10]"></span>
        </main>
      </body>
    </html>
  );
}
